# Exported from Render on 2025-08-03T03:45:23Z
services:
- type: web
  name: crm-proseller
  runtime: node
  repo: https://github.com/angel020588/crm-proseller
  plan: free
  envVars:
  - key: PORT
    sync: false
  - key: NODE_ENV
    sync: false
  - key: DATABASE_URL
    sync: false
  - key: PGPASSWORD
    sync: false
  - key: PGUSER
    sync: false
  - key: PGPORT
    sync: false
  - key: PGHOST
    sync: false
  - key: .PGDATABASE
    sync: false
  - key: SUPABASE_ANON_KEY
    sync: false
  - key: SUPABASE_URL
    sync: false
  - key: JWT_SECRET
    sync: false
  - key: MONGODB_URI
    sync: false
  - key: DB_PASS
    sync: false
  - key: DB_USER
    sync: false
  - key: DB_HOST
    sync: false
  - fromGroup: crm proseller
  region: oregon
  buildCommand: cd client && npm install && npm run build
  startCommand: node server/index.js
  autoDeployTrigger: commit
  previews:
    generation: automatic
version: "1"
